mainform/urls.py
from django.urls import path, include
from . import views

app_name='mainform'

urlpatterns = [
    path('', views.forms_all, name='allfrm'),
    path('add/', views.add_project, name='add_project'),
    path('frmd/<int:id>', views.form_detail, name='frm_detail'),    
]

map/urls.py
from django.conf.urls import include
from django.urls import path
#from geojson import GeoJSONLayerView
from .views import HomePageView, city_dataset, project_dataset, forms_all , viewmap, rgn_dataset, viewAllmap, registry_app, approve,home , mp_index, map_index, prj_index, project_view, project_search_view, projects, applicants, homepage, createInvestor, updateInvestor, deleteInvestor


urlpatterns = [
    path('', homepage, name='homepage'), #homepage/
    path('home', HomePageView, name='home'), #''
    path('rgstry/', registry_app, name='regist_form'),
    path('cities_data/', city_dataset, name='city'),  #cities_data/
    path('mapds/', rgn_dataset, name='regns'), #<int:id>
    path('approve/', approve, name='approve_form'),

    #path('', viewAllmap, name='viewall'), #''       
    path('maphome/', home, name='maphome'),
    #path('rgns_data/<int:id>', rgn_dataset, name='regns'), # rgns_data/

    path('projects_data/', project_dataset, name='projects_data'),
   #path('region_data/', HomePageView, name='region'),
    path('rgn/', forms_all, name='region'),
    path('mapd/<int:id>', viewmap, name='regions_details'), 

    path('allRegion', viewAllmap, name='allRegion'),
    path('viewMap/<int:id>', viewmap, name='viewMap'), #''
    path('map/', mp_index, name='map'),
    path('mapin/', map_index, name='mapin'),
    path('prjmap/', prj_index, name='prjmap'),
    path('prj/', project_search_view, name='prj'),
    path('prj/<int:id>/', project_view, name='prj'),
    path('prjall/', projects, name='prjall'),
    path('applicants/', applicants, name='applicants'),
    path('create_investor/', createInvestor, name='create_investor'),
    path('update_investor/<str:pk>/', updateInvestor, name='update_investor'),
    path('delete_investor/<str:pk>/', deleteInvestor, name='delete_investor'),

]

project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from app.views import indx
from map import views as map_view



urlpatterns = [
    path('', include('map.urls')), #map/
    path('pages/', include('pages.urls')), #,namespace='about'  pages/
    path('regist/', indx, name='regist'),
    #path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('mainform/', include('mainform.urls',namespace='frmu')),
    path('products/', include('products.urls')),

    #path('map/', map_view.mp_index, name='map'),

    #path('default/', include('app.urls')),
    
]
#www.mysite.com/'' will open main root
#www.mysite.com/pages will open pages

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

               

mainform/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.
area = (
    ('Indutry','Indutry'),
    ('Agriculture','Agriculture'),
    ('Tourism','Tourism'),
)

def image_upload(instance, filename):
    imagename , extension = filename.split(".")
    return "imgs/%s.%s"%(instance.id,extension)

class type_activity(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

class mainform(models.Model): # Table
    #today = datetime.date.today()
    #year = models.objects.filter(date__year = today.year)
    #year = models.DateField(input_formats=DATE_INPUT_FORMATS)

    owner = models.ForeignKey(User, related_name='projcet_owner', on_delete=models.CASCADE)
    project_name = models.CharField(max_length=130) # Column
    area = models.CharField(max_length=25,choices=area)
    type_activity = models.ForeignKey('type_activity',on_delete=models.CASCADE)
    location = models.CharField(max_length=26)
    regist_date = models.DateField(auto_now=False)
    description = models.TextField(max_length=200)
    person = models.CharField(max_length=88)
    possition = models.CharField(max_length=50)
    nation = models.CharField(max_length=30)
    passport = models.CharField(max_length=25)
    phone1 = models.CharField(max_length=16)
    phone2 = models.CharField(max_length=16)
    address = models.CharField(max_length=26)
    email = models.EmailField(max_length=25)
    image = models.ImageField(upload_to=image_upload)
    slug = models.SlugField(blank=True, null=True)

    def save(self,*args, **kwargs):
        self.slug =slugify(self.project_name)# slugify cut spase and putt -
        super(mainform,self).save(*args,**kwargs)


    def __str__(self):
        return self.project_name
    
class get_opportunnity(models.Model):
    project_name = models.ForeignKey(mainform, related_name='get_oppor', on_delete=models.CASCADE)
    name = models.CharField(max_length=55)
    email = models.EmailField(max_length=50)
    website = models.URLField()
    passport_pic = models.FileField(upload_to='registred/')
    notes = models.TextField(max_length=200)
    created_at= models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

mainform/views.py
from django.shortcuts import redirect, render
from .models import mainform
from django.core.paginator import Paginator
from .form import RegistryForm, ProjectForm
from django.urls import reverse

# Create your views here.

def forms_all(request):
    forms_all = mainform.objects.all()
    paginator = Paginator(forms_all, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context ={'allfrm':page_obj} # Template Name #forms_all
    return render(request,'form_all.html',context)


def form_detail(request, id):
    form_detail = mainform.objects.get(id=id)
    if request.method=='POST':
        form = RegistryForm(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.project_name = form_detail
            myform.save()
    else:
        form = RegistryForm()    
    context = {'frm':form_detail,'form_rgst':form}
    return render(request,'form_detail.html',context)

def add_project(request):
    if request.method=='POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save()
            return redirect(reverse('frmu:allfrm'))
    else:
        form = ProjectForm()
    return render(request,'add_project.html',{'form_r':form})
    

mainform/templates/add_project.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load bootstrap4 %}

{% block body %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Add New Project</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <div class="apply_job_form white-bg">
                    <h4>Post New Project</h4>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form_r %}
                        {%buttons%}
                        <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                        {% endbuttons %}

                        {% bootstrap_button button_type="submit" content="OK" %}
                        {% bootstrap_button button_type="reset" content="Cancel" %}

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

mainform/templates/form_all.html
{% extends 'base.html' %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{allfrm.count}} + Forms Registred</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="job_filter white-bg">
                    <div class="form_inner white-bg">
                        <h3>Filter</h3>
                        <form action="#">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="single_field">
                                        <input type="text" placeholder="Search keyword">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="single_field">
                                        <select class="wide">
                                            <option data-display="Location">Location</option>
                                            <option value="1">Rangpur</option>
                                            <option value="2">Dhaka </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="single_field">
                                        <select class="wide">
                                            <option data-display="Category">Category</option>
                                            <option value="1">Category 1</option>
                                            <option value="2">Category 2 </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="single_field">
                                        <select class="wide">
                                            <option data-display="Experience">Experience</option>
                                            <option value="1">Experience 1</option>
                                            <option value="2">Experience 2 </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="single_field">
                                        <select class="wide">
                                            <option data-display="Job type">Job type</option>
                                            <option value="1">full time 1</option>
                                            <option value="2">part time 2 </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="single_field">
                                        <select class="wide">
                                            <option data-display="Qualification">Qualification</option>
                                            <option value="1">Qualification 1</option>
                                            <option value="2">Qualification 2</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="single_field">
                                        <select class="wide">
                                            <option data-display="Gender">Gender</option>
                                            <option value="1">male</option>
                                            <option value="2">female</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="range_wrap">
                        <label for="amount">Price range:</label>
                        <div id="slider-range"></div>
                        <p>
                            <input type="text" id="amount" readonly
                                style="border:0; color:#7A838B; font-size: 14px; font-weight:400;">
                        </p>
                    </div>
                    <div class="reset_btn">
                        <button class="boxed-btn3 w-100" type="submit">Reset</button>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="recent_joblist_wrap">
                    <div class="recent_joblist white-bg ">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <h4>Job Listing</h4>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="job_lists m-0">
                    <div class="row">
                        {% for frms in allfrm %}
                        <div class="col-lg-12 col-md-12">
                            <div class="single_jobs white-bg d-flex justify-content-between">
                                <div class="jobs_left d-flex align-items-center">
                                    <div class="thumb">
                                        <img src="img/svg_icon/1.svg" alt="">
                                    </div>
                                    <div class="jobs_conetent">
                                        <a href="{% url 'frmu:frm_detail' frms.id %}">
                                            <h4>{{frms}}</h4>
                                        </a>
                                        <div class="links_locat d-flex align-items-center">
                                            <div class="location">
                                                <p> <i class="fa fa-map-marker"></i>
                                                    {{frms.nation}}</p>
                                            </div>
                                            <div class="location">
                                                <p> <i class="fa fa-clock-o"></i>
                                                    {{frms.area}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="jobs_right">
                                    <div class="apply_now">
                                        <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                        <a href="{% url 'frmu:frm_detail' frms.id %}" class="boxed-btn3">Apply Now</a>
                                    </div>
                                    <div class="date">
                                        <p>{{frms.regist_date|date:'o-m-d'}}</p>

                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% if allfrm.has_other_pages %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="pagination_wrap">
                                <ul>
                                    {% if allfrm.has_previous %}
                                    <li><a href="?page={{allfrm.previous_page_number}}"> <i class="ti-angle-left"></i>
                                        </a></li>
                                    {% endif %}

                                    {% for i in allfrm.paginator.page_range %}
                                    <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                    {% endfor %}

                                    {% if allfrm.has_next %}
                                    <li><a href="?page={{allfrm.next_page_number}}"> <i class="ti-angle-right"></i> </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- job_listing_area_end  -->

{% endblock body %}

mainform/templates/form_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load bootstrap4 %}

{% block body %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{frm}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb">
                                <img src="img/svg_icon/1.svg" alt="">
                            </div>
                            <div class="jobs_conetent">
                                <a href="#">
                                    <h4>{{frm}}</h4>
                                </a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i>{{frm.nation}}</p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i>{{frm.area}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="descript_wrap white-bg">
                    <div class="single_wrap">
                        <h4>Job description</h4>
                        <p>{{frm.description}}</p>
                    </div>
                </div>
                <div class="apply_job_form white-bg">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form_rgst %}
                        {%buttons%}
                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                        {% endbuttons %}
                        {% bootstrap_button button_type="submit" content="OK" %}
                        {% bootstrap_button button_type="reset" content="Cancel" %}
                    </form>
                </div>

            </div>
            <div class="col-lg-4">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>Job Summery</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>Registred on: <span>{{frm.regist_date|date:'o-m-d'}}</span></li>
                            <li>Phone Number: <span>{{frm.phone1}}</span></li>
                            <li>Phone Number: <span>{{frm.phone2}}</span></li>
                            <li>Location: <span>{{frm.location}}</span></li>
                            <li>Email: <span>{{frm.email}}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="share_wrap d-flex">
                    <span>Share at:</span>
                    <ul>
                        <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                    </ul>
                </div>
                <div class="job_location_wrap">
                    <div class="job_lok_inner">
                        <div id="map" style="height: 200px;"></div>
                        <script>
                            function initMap() {
                                var uluru = { lat: -25.363, lng: 131.044 };
                                var grayStyles = [
                                    {
                                        featureType: "all",
                                        stylers: [
                                            { saturation: -90 },
                                            { lightness: 50 }
                                        ]
                                    },
                                    { elementType: 'labels.text.fill', stylers: [{ color: '#ccdee9' }] }
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                    center: { lat: -31.197, lng: 150.744 },
                                    zoom: 9,
                                    styles: grayStyles,
                                    scrollwheel: false
                                });
                            }

                        </script>
                        <script
                            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}