mainform/urls.py
from django.urls import path, include
from . import views

app_name='mainform'

urlpatterns = [
    path('', views.forms_all, name='allfrm'),
    path('add/', views.add_project, name='add_project'),
    path('frmd/<int:id>', views.form_detail, name='frm_detail'),    
]

map/urls.py
from django.conf.urls import include
from django.urls import path
#from geojson import GeoJSONLayerView
from .views import HomePageView, city_dataset, project_dataset, forms_all , viewmap, rgn_dataset, viewAllmap, registry_app, approve,home , mp_index, map_index, prj_index, project_view, project_search_view, projects, applicants, homepage, createInvestor, updateInvestor, deleteInvestor


urlpatterns = [
    path('', homepage, name='homepage'), #homepage/
    path('home', HomePageView, name='home'), #''
    path('rgstry/', registry_app, name='regist_form'),
    path('cities_data/', city_dataset, name='city'),  #cities_data/
    path('mapds/', rgn_dataset, name='regns'), #<int:id>
    path('approve/', approve, name='approve_form'),

    #path('', viewAllmap, name='viewall'), #''       
    path('maphome/', home, name='maphome'),
    #path('rgns_data/<int:id>', rgn_dataset, name='regns'), # rgns_data/

    path('projects_data/', project_dataset, name='projects_data'),
   #path('region_data/', HomePageView, name='region'),
    path('rgn/', forms_all, name='region'),
    path('mapd/<int:id>', viewmap, name='regions_details'), 

    path('allRegion', viewAllmap, name='allRegion'),
    path('viewMap/<int:id>', viewmap, name='viewMap'), #''
    path('map/', mp_index, name='map'),
    path('mapin/', map_index, name='mapin'),
    path('prjmap/', prj_index, name='prjmap'),
    path('prj/', project_search_view, name='prj'),
    path('prj/<int:id>/', project_view, name='prj'),
    path('prjall/', projects, name='prjall'),
    path('applicants/', applicants, name='applicants'),
    path('create_investor/', createInvestor, name='create_investor'),
    path('update_investor/<str:pk>/', updateInvestor, name='update_investor'),
    path('delete_investor/<str:pk>/', deleteInvestor, name='delete_investor'),

]

project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from app.views import indx
from map import views as map_view



urlpatterns = [
    path('', include('map.urls')), #map/
    path('pages/', include('pages.urls')), #,namespace='about'  pages/
    path('regist/', indx, name='regist'),
    #path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('mainform/', include('mainform.urls',namespace='frmu')),
    path('products/', include('products.urls')),

    #path('map/', map_view.mp_index, name='map'),

    #path('default/', include('app.urls')),
    
]
#www.mysite.com/'' will open main root
#www.mysite.com/pages will open pages

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

               

templates/base.html
{% load static %}
{% load leaflet_tags %}
{% leaflet_js %}
{% leaflet_css %}


<!DOCTYPE html>
<html lang="en">

<head>
    <style type="text/css">
        .image-thubail {
            height: 200px;
            object-fit: cover;
        }

        #gis {
            width: 100%;
            height: 680px;
        }
    </style>

    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard </title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="{% static 'assets/img/favicon1.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon1.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.css' %}">

    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">

    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css'%}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css'%}" rel="stylesheet">

    <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="/" class="logo d-flex align-items-center">
                <img src="assets/img/logo1.png" alt="">
                <span class="d-none d-lg-block">Libya Invesment Map</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div><!-- End Search Bar -->

    </header> <!-- End header -->

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar" style="padding: 11px 09px; height:280px">
        <ul class="sidebar-nav" id="sidebar-nav">
            <li style="display: inline-block;text-align: center;background-color:#0094ff;"><a class="navbar-brand"
                    ui-sref="sitesDamages.sitesList" style="padding: 11px 09px; height:auto" title="events"><i
                        class="glyphicon glyphicon-exclamation-sign"></i></a>
            </li>

            <li style="display: inline-block;text-align: center;background-color:red;" class="nav-item">
                <a class="nav-link " href="/">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->
            <li style="display: inline-block;text-align: center;background-color:red;"><a class="navbar-brand"
                    ui-sref="sites.list" style="padding: 11px 09px; height:auto" title="sites"><i
                        class="glyphicon glyphicon-tree-conifer"></i></a></li>


            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="mapin">
                    <i class="bi bi-menu-button-wide"></i><span>Components</span><i
                        class="bi bi-chevron-down ms-auto"></i>

                </a>
            </li><!-- End Components Nav -->


            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-journal-text"></i><span>Forms</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
            </li><!-- End Forms Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse"
                    href="{% url 'prjall' %}">
                    <i class="bi bi-layout-text-window-reverse"></i><span>Tables</span><i
                        class="bi bi-chevron-down ms-auto"></i>
                </a>
            </li><!-- End Tables Nav -->
        </ul>
    </aside>



    <!-- ======= Sidebar ======= -->


    {% block body %}



    {% endblock body %}

    {% leaflet_map "gis" callback="window.out_layers" %}





    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>Pib </span></strong>. All Rights Reserved
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script type="text/javascript" src="{% static 'leaflet-groupedlayercontrol/leaflet.ajax.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.js' %}"></script>
    <script type="text/javascript" src="{% static 'leaflet-groupedlayercontrol/leaflet-routing-machine.js' %}"></script>


    <script src="{% static 'assets/js/chart.js"></script>
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>



</body>

</html>

templates/base1.html
{% load static %}
{% load leaflet_tags %}
{% leaflet_js %}
{% leaflet_css %}


<!doctype html>

<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Main Form</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!--
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <script src="https://unpkg.com/htmx.org@1.6.1"></script>
-->
    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.css' %}">



    <link rel="stylesheet" href="{% static 'dist/css/select2.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/responsive.css"> -->

    <style type="text/css">
        .image-thubail {
            height: 200px;
            object-fit: cover;
        }

        #gis {
            width: 80%;
            height: 680px;
        }
    </style>
</head>

<body>
    <link rel="stylesheet" href="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.css' %}">
    <script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.js' %}"></script>
    <script type="text/javascript" src="{% static 'routing/leaflet-routing-machine.js' %}"></script>

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-7 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url 'about' %}">Login</a></li>
                                            <li><a href="{% url 'gallery' %}">Gallery</a></li>
                                            <li><a href="{% url 'frmu:allfrm' %}">Form Apply</a></li>
                                            <li><a href="{% url 'frmu:add_project' %}">Add Form </a></li>
                                            <li><a href="{% url 'region' %}">Add Map </a></li>
                                            <li><a href="#">pages <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="candidate.html">Candidates </a></li>
                                                    <li><a href="job_details.html">job details </a></li>
                                                    <li><a href="">elements</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li><a href="contact.html">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="#">Log in</a>
                                    </div>
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="#">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    {% block body %}



    {% endblock body %}

    {% leaflet_map "gis" callback="window.out_layers" %}


    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                eng7wissam@gmail.com <br>
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                            template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->

    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- <script src="{% static 'js/gijgo.min.js' %}"></script> -->
    <script src="{% static 'js/range.js' %}"></script>

    <!--contact js-->
    <script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.js' %}"></script>
    <script src="js/contact.js"></script>
    <script src="js/jquery.ajaxchimp.min.js"></script>
    <script src="js/jquery.form.js"></script>
    <script src="js/jquery.validate.min.js"></script>
    <script src="js/mail-script.js"></script>
    <script src="js/main.js"></script>

    <script>
        $(function () {
            $("#slider-range").slider({
                range: true,
                min: 0,
                max: 24600,
                values: [750, 24600],
                slide: function (event, ui) {
                    $("#amount").val("$" + ui.values[0] + " - $" + ui.values[1] + "/ Year");
                }
            });
            $("#amount").val("$" + $("#slider-range").slider("values", 0) +
                " - $" + $("#slider-range").slider("values", 1) + "/ Year");
        });
    </script>

    {% block scripts %}

    {% endblock %}

</body>

</html>