map/urls.py
from django.conf.urls import include
from django.urls import path
#from geojson import GeoJSONLayerView
from .views import HomePageView, city_dataset, project_dataset, forms_all , viewmap, rgn_dataset, viewAllmap, registry_app, approve,home , mp_index, map_index, prj_index, project_view, project_search_view, projects, applicants, homepage, createInvestor, updateInvestor, deleteInvestor


urlpatterns = [
    path('', homepage, name='homepage'), #homepage/
    path('home', HomePageView, name='home'), #''
    path('rgstry/', registry_app, name='regist_form'),
    path('cities_data/', city_dataset, name='city'),  #cities_data/
    path('mapds/', rgn_dataset, name='regns'), #<int:id>
    path('approve/', approve, name='approve_form'),

    #path('', viewAllmap, name='viewall'), #''       
    path('maphome/', home, name='maphome'),
    #path('rgns_data/<int:id>', rgn_dataset, name='regns'), # rgns_data/

    path('projects_data/', project_dataset, name='projects_data'),
   #path('region_data/', HomePageView, name='region'),
    path('rgn/', forms_all, name='region'),
    path('mapd/<int:id>', viewmap, name='regions_details'), 

    path('allRegion', viewAllmap, name='allRegion'),
    path('viewMap/<int:id>', viewmap, name='viewMap'), #''
    path('map/', mp_index, name='map'),
    path('mapin/', map_index, name='mapin'),
    path('prjmap/', prj_index, name='prjmap'),
    path('prj/', project_search_view, name='prj'),
    path('prj/<int:id>/', project_view, name='prj'),
    path('prjall/', projects, name='prjall'),
    path('applicants/', applicants, name='applicants'),
    path('create_investor/', createInvestor, name='create_investor'),
    path('update_investor/<str:pk>/', updateInvestor, name='update_investor'),
    path('delete_investor/<str:pk>/', deleteInvestor, name='delete_investor'),

]

project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from app.views import indx
from map import views as map_view



urlpatterns = [
    path('', include('map.urls')), #map/
    path('pages/', include('pages.urls')), #,namespace='about'  pages/
    path('regist/', indx, name='regist'),
    #path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('mainform/', include('mainform.urls',namespace='frmu')),
    path('products/', include('products.urls')),

    #path('map/', map_view.mp_index, name='map'),

    #path('default/', include('app.urls')),
    
]
#www.mysite.com/'' will open main root
#www.mysite.com/pages will open pages

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

               

approve/models.py
from django.db import models

# Create your models here.

map/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.gis.db import models as gis_models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

#from django.contrib.gis import gdal
#from django.db.models import Manager as GeoManager
#from django.db.models.manager import Manager
#from django.contrib.gis.gdal.libgdal import lgdal
# Create your models here.

class House(models.Model):
    name = models.CharField(max_length=44)
    location = gis_models.PointField(srid=4326)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural='Houses'

def image_upload(instance, filename):
    imagename , extension = filename.split(".")
    return "imgs/%s.%s"%(instance.id,extension)

class Area(models.Model):
    area = models.CharField(max_length=25)

    def __str__(self):
        return self.area


class type_activity(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    
class Regions(models.Model):
    name = models.CharField(max_length=40)
    name_of = models.CharField(max_length=40)
    no_of = models.IntegerField()
    type = models.CharField(max_length=30)
    geom = gis_models.MultiPolygonField(srid=4326)
    
    def __str__(self):
        return self.name

class Cities_Ly(models.Model):
    name_ar = models.CharField(max_length=85)
    name_en = models.CharField(max_length=47)
    region_name = models.CharField(max_length=43)
    latitude = models.FloatField()
    longitude = models.FloatField()
    region_no = models.IntegerField()
    region = models.ForeignKey(Regions,on_delete=models.CASCADE, null=True)
    geom = gis_models.MultiPolygonField(srid=4326)
    def __unicode__(self):
        return self.geom

    
class Municip(models.Model):
    name = models.CharField(max_length=254)
    region = models.ForeignKey(Regions,on_delete=models.CASCADE, null=True)
    latitude = models.FloatField()
    longitude = models.FloatField() 
    geom = gis_models.MultiPointField(srid=4326)
    objects =gis_models.Manager()
    def __str__(self):
        #return (self.latitude, self.longitude)
       return self.name


class Projects(models.Model):
    proj_name = models.CharField(max_length=254)
    proj_no = models.PositiveIntegerField()
    region = models.ForeignKey(Regions,on_delete=models.CASCADE, verbose_name='ادخل المنطقة')
    city = models.CharField(max_length=254)
    location = models.ForeignKey(Municip,on_delete=models.CASCADE) 
    area = models.ForeignKey(Area,on_delete=models.CASCADE, verbose_name='ادخل المجال')
    type_activity = models.ForeignKey(type_activity,on_delete=models.CASCADE, null=True)
    regist_date = models.DateField(auto_now=False, null=True)
    description = models.TextField(max_length=200, null=True, blank=True)
    proj_id = models.CharField(max_length=25, default=0)


    def save(self, *args , **kwargs):        
         #+ str(self.regist_date.year)
        self.proj_id= str(self.region.id) + str(self.area.id) + str(self.proj_no) #+ str(self.ID) 
        super().save(*args , **kwargs)

    def __str__(self):
        return self.proj_name

class Applicants(models.Model): # Table
    project = models.ForeignKey(Projects, on_delete=models.CASCADE, related_name='applicants')
    owner = models.ForeignKey(User, related_name='app_owner', on_delete=models.CASCADE)
    person = models.CharField(max_length=88)
    possition = models.CharField(max_length=50)
    nation = models.CharField(max_length=30)
    passport = models.CharField(max_length=25)
    phone1 = models.CharField(max_length=16)
    phone2 = models.CharField(max_length=16)
    address = models.CharField(max_length=26)
    email = models.EmailField(max_length=25)
    regist_date = models.DateField(auto_now=False)


    def __str__(self):
        return self.person
    
class Investors(models.Model):
    project = models.ForeignKey(Projects, on_delete=models.CASCADE, related_name='investors')
    name = models.CharField(max_length=30)
    nation = models.CharField(max_length=30)
    type_currency = models.CharField(max_length=25)
    phone = models.CharField(max_length=16)
    email = models.EmailField(max_length=25)
    percent =models.DecimalField(max_digits=5, decimal_places=2)
    invest_cost =models.FloatField() 
    #proj_id = models.ForeignKey(Projects.proj_id, on_delete=models.CASCADE)


    def __str__(self):
        return self.name    


class Locations(models.Model):
    project = models.ForeignKey(Projects, on_delete=models.CASCADE, null=True,related_name='locations')
    proj_no = models.FloatField()
    proj_name = models.CharField(max_length=254)
    region = models.ForeignKey(Regions,on_delete=models.CASCADE, null=True, verbose_name='ادخل المنطقة')
    #location = models.ForeignKey(Municip,on_delete=models.CASCADE, null=True) 
    city = models.CharField(max_length=75, null=True)
    area = models.ForeignKey(Area,on_delete=models.CASCADE, null=True)
    field = models.CharField(max_length=36, null=True)
    regist_date = models.DateField(auto_now=True, null=True)
    description = models.TextField(max_length=200, null=True, blank=True)
    active = models.BooleanField(default=True, null=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True) 
    geom = gis_models.MultiPointField(srid=4326, null=True)
    objects =gis_models.Manager()

    def __str__(self):  #unicode
        return self.proj_name
    

class Incidences(models.Model):
    name = models.CharField(max_length=30)
    #location = models.CharField(max_length=30)
    location = gis_models.PointField(srid=4326) # stid=2453 null=True
    objects =gis_models.Manager()
    #objects = GeoManager()
    def __unicode__(self):
        return self.name    
    class Meta:
        verbose_name_plural = 'Incidences'

class Search(models.Model):
    address = models.CharField(max_length=200, null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.address

map/forms.py
from django import forms
from datetime import datetime

from django.urls import reverse_lazy
from .models import Search, Regions, Applicants, Municip, Locations, Projects, Investors
from django.contrib.gis.db import models as gis_models
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
# lable, initial, disable , help_text,
# widget=forms.PasswordInput, required

class SearchForm(forms.ModelForm):
    address = forms.CharField(label='')
    class Meta:
        model = Search
        fields = ['address', ]

class ApplicantForm(forms.ModelForm):
        class Meta:
            model = Applicants
            fields = '__all__'

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['region'].queryset = Regions.objects.all()

            if 'region' in self.data:
                             self.fields['region'].queryset = Regions.objects.all()


class rgstForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_action = reverse_lazy('approve_form')
        self.helper.form_method='GET'
        self.helper.add_input(Submit('submit', 'Submit'))

    Executive_type=(
        (1,'تحت التاسيس'),
        (2,'تحت التنفيذ'),
        (3,'دخلت التشغيل'),
    )
    name = forms.CharField(widget=forms.TextInput(attrs={
             'hx-get': reverse_lazy('approve_form'), 'hx-trigger': 'keyup'
        }))
    executive = forms.ChoiceField(
        choices=Executive_type, widget=forms.RadioSelect()
    )
    #regist_date = forms.DateField(widget=forms.DateInput(format = '%d-%m-%Y' ,attrs={'type':'date', 'max':datetime.today()}))

    date_of_birth = forms.DateField(localize=True,widget=forms.DateInput(format = '%Y-%mm-%dd',attrs={'type': 'date'}))
    
    #issue_date = forms.DateField(widget=forms.DateInput(format = '%d/%m/%Y'), input_formats=settings.DATE_INPUT_FORMATS)


class RegionForm(forms.ModelForm):
        #name = forms.CharField(max_length=40)
        #name_of = forms.CharField(max_length=40)
        #no_of = forms.IntegerField()
        #type = forms.CharField(max_length=30, label='المنطقة') #, initial='Enter Name here'   widget=forms.Textarea(attrs={'style': "width:100%;"}), 
        #geom = gis_models.MultiPolygonField(srid=4326)
        class Meta:
            model = Regions
            fields = '__all__' #['name','type','no_of','geom']

class MunicipForm(forms.ModelForm):
      name =forms.CharField(label='')
      class Meta:
            model = Municip
            fields = ['name', ]

class LocationsForm(forms.ModelForm):
      class Meta:
            model= Locations
            fields = ['proj_name', ]

class ProjectsForm(forms.ModelForm):
      class Meta:
            model= Projects
            fields = ['proj_name', ]

class InvestorForm(forms.ModelForm):
      class Meta:
            model= Investors
            fields = '__all__' 

approve/views.py
from django.shortcuts import render

# Create your views here.

map/templates/applicants.html
{% extends 'base.html' %}
{% block body %}
{% include 'status.html' %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="row">
    <div class="col-md-5">
        <h5> Applicants </h5>
        <div class="card card-body">
            <a class="btn btn-primary btn-sm btn-block" href=""></a>
        </div>
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th> Name</th>
                    <th> Nation</th>
                    <th>Project No</th>


                </tr>
                {% for applicant in applicants %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'prj' applicant.project.id %}">View</a></td>
                    <td>{{applicant.person}} </td>
                    <td>{{applicant.nation}} </td>
                    <td>{{applicant.project}} </td>


                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="col-md-7">
        <h5> Investors </h5>
        <div class="card card-body">
            <a class="btn btn-primary btn-sm btn-block" href=""></a>
        </div>
        <table class="table table-sm">
            <tr>
                <th>Investor No</th>
                <th>Investor Name</th>
                <th> Nation </th>
            </tr>
            {% for investor in investors %}
            <tr>
                <td><a class="btn btn-sm btn-info" href="{% url 'prj' investor.project.id %}">View</a></td>
                <td>{{investor.name}} </td>
                <td>{{investor.nation}} </td>
                <td>{{investor.project}} </td>

                <td><a class="btn btn-outline-info btn-sm btn-block" href="">Update</a></td>
                <td><a class="btn btn-outline-danger btn-sm btn-block" href="">Delete</a></td>

            </tr>
            {% endfor %}
        </table>
    </div>

</div>
{% endblock body %}

map/templates/approve.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    {% crispy form_approve %}
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->




{% endblock body %}

map/templates/dashboard.html
{% extends 'base.html' %}
{% block body %}
{% include 'status.html' %}


<div class="row">
    <div class="col-md-5">
        <h5> Applicants </h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-primary btn-sm btn-block" href="">Create Applicant</a>
            <table class="table table-sm">
                <tr>
                    <th> </th>
                    <th> Name</th>
                    <th> Nation</th>
                    <th>Project Name</th>
                </tr>
                {% for applicant in applicants %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'prj' applicant.project.id %}">View</a></td>
                    <td>{{applicant.person}} </td>
                    <td>{{applicant.nation}} </td>
                    <td>{{applicant.project}} </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="col-md-7">
        <h5> Investors </h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-primary btn-sm btn-block" href="{% url 'create_investor' %}">Create Investor</a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Investor Name</th>
                    <th> Nation </th>
                    <th> Project Name </th>

                </tr>
                {% for investor in investors %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'prj' investor.id %}">View</a></td>
                    <td>{{investor.name}} </td>
                    <td>{{investor.nation}} </td>
                    <td>{{investor.project}} </td>

                    <td><a class="btn btn-outline-info btn-sm btn-block"
                            href="{% url 'update_investor' investor.id %}">Update</a></td>
                    <td><a class="btn btn-outline-danger btn-sm btn-block"
                            href="{% url 'delete_investor' investor.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% block script %}
<div class="row">
    <div class="col-md-5">
        <div class="card card-body">

            <div id="map" style="height: 50px; width: 600px;">
                <script type="text/javascript">
                    function out_layers(map, options) {
                        var osm = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                            maxZoom: 19,
                            attribution: '© OpenStreetMap'
                        });

                        var osmHOT = L.tileLayer('https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {
                            maxZoom: 19,
                            attribution: '© OpenStreetMap contributors, Tiles style by Humanitarian OpenStreetMap Team hosted by OpenStreetMap France'
                        });
                        var openTopoMap = L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
                            maxZoom: 19,
                            attribution: 'Map data: © OpenStreetMap contributors, SRTM | Map style: © OpenTopoMap (CC-BY-SA)'
                        });

                        var googleSat = L.tileLayer('http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}', {
                            maxZoom: 20,
                            subdomains: ['mt0', 'mt1', 'mt2', 'mt3']
                        });
                        // googleSat.addTo(pibMap);

                        var googleHybrid = L.tileLayer('http://{s}.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}', {
                            maxZoom: 20,
                            subdomains: ['mt0', 'mt1', 'mt2', 'mt3']
                        });

                        var datasets = new L.GeoJSON.AJAX("{% url 'city' %}", {
                            style: function colors(feature) {
                                switch (feature.properties.pk) {
                                    case '1':
                                        return {
                                            radius: 8,
                                            fillColor: 'blue',
                                            weight: 2,
                                            opacity: 1,
                                            color: 'orange',
                                            fillOpacity: 0.7
                                        };
                                        break;
                                    case '2':
                                        return {
                                            fillColor: '#285078',
                                            weight: 2,
                                            opacity: 1,
                                            color: 'orange',
                                            fillOpacity: 0.7
                                        };
                                        break;
                                    case '3':
                                        return {
                                            fillColor: '#a0c8f0',
                                            weight: 2,
                                            opacity: 1,
                                            color: 'orange',
                                            fillOpacity: 0.7
                                        };
                                        break;
                                    case '4':
                                        return {
                                            fillColor: '#FCF3CF ',
                                            weight: 2,
                                            opacity: 1,
                                            color: 'orange',
                                            fillOpacity: 0.7
                                        };
                                        break;
                                }
                            },
                            onEachFeature: function (feature, layer) {
                                layer.bindPopup(feature.properties.name_ar.toString());
                            }
                        });

                        var points = new L.GeoJSON.AJAX("{% url 'projects_data' %}", {
                            onEachFeature: function (feature, layer) {
                                layer.bindPopup(feature.properties.proj_name.toString());
                            }
                        });

                        datasets.addTo(map);
                        points.addTo(map);

                        var baseMaps = {
                            "OpenStreetMap": osm,
                            "OpenStreetMap.HOT": osmHOT,
                            "openTopoMap": openTopoMap,
                            "Satallite": googleSat,
                            "googleHybrid": googleHybrid,

                        };

                        var overlayMaps = {
                            "region": datasets,
                            "project_na": points,
                        };
                        var layerControl = L.control.layers(baseMaps, overlayMaps).addTo(map);
                    }
                </script>
            </div>
        </div>
    </div>
</div>
{% endblock script %}

{% endblock body %}

map/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
        </div>
    </div>
</div>
</div>
<!--/ bradcam_area  -->

<div class="row">
    <div class="col-md-6">
        <div class="card card-body">

            <p> Are you sur want delete "{{item}}" ?</p>

            <form action="{% url 'delete_investor' item.id %}" method="POST">
                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'homepage' %}">Cancel</a>

                <input class="btn btn-danger" type="submit" name="Confirm">
            </form>
        </div>
    </div>
</div>
{% endblock body %}

map/templates/index.html
{% extends 'base.html' %}
{% block body %}

<style type="text/css">
    #gis {
        width: 80%;
        height: 600px;
    }
</style>
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3></h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div id="map" style="height: 50px; width: 600px;">
    <h1 class="text-center mb-8 section-heading border-bottom pb-2">Libya investment Map </h1>
</div>

{% block script %}
<div id="map" style="height: 50px; width: 600px;">
    <script type="text/javascript">
        function out_layers(map, options) {
            var osm = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '© OpenStreetMap'
            });

            var osmHOT = L.tileLayer('https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '© OpenStreetMap contributors, Tiles style by Humanitarian OpenStreetMap Team hosted by OpenStreetMap France'
            });
            var openTopoMap = L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: 'Map data: © OpenStreetMap contributors, SRTM | Map style: © OpenTopoMap (CC-BY-SA)'
            });

            var googleSat = L.tileLayer('http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}', {
                maxZoom: 20,
                subdomains: ['mt0', 'mt1', 'mt2', 'mt3']
            });
            // googleSat.addTo(pibMap);

            var googleHybrid = L.tileLayer('http://{s}.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}', {
                maxZoom: 20,
                subdomains: ['mt0', 'mt1', 'mt2', 'mt3']
            });

            var datasets = new L.GeoJSON.AJAX("{% url 'city' %}", {
                style: function colors(feature) {
                    switch (feature.properties.pk) {
                        case '1':
                            return {
                                radius: 8,
                                fillColor: 'blue',
                                weight: 2,
                                opacity: 1,
                                color: 'orange',
                                fillOpacity: 0.7
                            };
                            break;
                        case '2':
                            return {
                                fillColor: '#285078',
                                weight: 2,
                                opacity: 1,
                                color: 'orange',
                                fillOpacity: 0.7
                            };
                            break;
                        case '3':
                            return {
                                fillColor: '#a0c8f0',
                                weight: 2,
                                opacity: 1,
                                color: 'orange',
                                fillOpacity: 0.7
                            };
                            break;
                        case '4':
                            return {
                                fillColor: '#FCF3CF ',
                                weight: 2,
                                opacity: 1,
                                color: 'orange',
                                fillOpacity: 0.7
                            };
                            break;
                    }
                },
                onEachFeature: function (feature, layer) {
                    layer.bindPopup(feature.properties.name_ar.toString());
                }
            });

            var points = new L.GeoJSON.AJAX("{% url 'projects_data' %}", {
                onEachFeature: function (feature, layer) {
                    layer.bindPopup(feature.properties.proj_name.toString());
                }
            });

            datasets.addTo(map);
            points.addTo(map);

            var baseMaps = {
                "OpenStreetMap": osm,
                "OpenStreetMap.HOT": osmHOT,
                "openTopoMap": openTopoMap,
                "Satallite": googleSat,
                "googleHybrid": googleHybrid,

            };

            var overlayMaps = {
                "region": datasets,
                "project_na": points,
            };
            var layerControl = L.control.layers(baseMaps, overlayMaps).addTo(map);
        }
    </script>
</div>
{% endblock script %}

{% endblock body %}

map/templates/investor_form.html
{% extends 'base.html' %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
        </div>
    </div>
</div>
</div>
<!--/ bradcam_area  -->
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {{form}}

                <input type="submit" name="Submit">
            </form>
        </div>
    </div>
</div>

{% endblock body %}

map/templates/map_detail.html
{% extends 'base.html' %}

{% block body %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{regions_details}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb">
                                <img src="img/svg_icon/1.svg" alt="">
                            </div>
                            <div class="jobs_conetent">
                                <a href="#">
                                    <h4>{{regions_details}}</h4>
                                </a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i>{{regions_details.name}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

map/templates/registry.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<style>
    #id_region {
        width: 80%;
    }
</style>

{% block body %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<div class="job_listing_area plus_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="apply_job_form white-bg">
                    <form action="{% url 'regist_form' %}" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary mt-4">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock body %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js"
    integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js">

</script>

<script>
    $(document).ready(function () {
        $('#id_region').select2();
    });
</script>

{% endblock %}